#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Areas\Admin\Views\File\Index.cshtml"
    using System.Diagnostics;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Admin\Views\File\Index.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Admin\Views\File\Index.cshtml"
    using NewLife.Cube.Admin;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/File/Index.cshtml")]
    public partial class _Areas_Admin_Views_File_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_File_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\File\Index.cshtml"
  
    //ViewBag.Title = "服务器信息";
    var fs = Model as List<FileItem>;
    var r = ViewBag.Current as String;
    var clips = ViewBag.Clip as ICollection<FileItem>;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n    <form");

WriteAttribute("action", Tuple.Create(" action=\"", 290), Tuple.Create("\"", 311)
, Tuple.Create(Tuple.Create("", 299), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File")
, 299), false)
);

WriteLiteral(" id=\"tool\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"ace-icon fa fa-check\"");

WriteLiteral("></i>\r\n            </span>\r\n            <input");

WriteLiteral(" name=\"r\"");

WriteLiteral(" type=\"search\"");

WriteLiteral(" id=\"r\"");

WriteAttribute("value", Tuple.Create(" value=\"", 543), Tuple.Create("\"", 553)
            
            #line 16 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 551), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 551), false)
);

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"目标路径\"");

WriteLiteral(" />\r\n            <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(" >\r\n                    <span");

WriteLiteral(" class=\"glyphicon glyphicon-folder-open icon-on-right bigger-110\"");

WriteLiteral("></span>\r\n                    打开\r\n                </button>\r\n            </span>\r" +
"\n        </div>\r\n\r\n       \r\n        <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n            <input");

WriteLiteral(" name=\"ufile\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ufile\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"文件\"");

WriteLiteral(" />\r\n            <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" onclick=\"$(\'input[id=file]\').click();\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"glyphicon glyphicon-cloud-upload icon-on-right bigger-110\"");

WriteLiteral("></span>\r\n                    选择文件\r\n                </button>\r\n            </span" +
">\r\n            <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" style=\"margin-left:5px;\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" onclick=\"$(\'#tool\').attr(\'action\', \'/Admin/File/Upload\');$(\'#tool\').attr(\'enctyp" +
"e\', \'multipart/form-data\'); return true;\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"glyphicon glyphicon-plus icon-on-right bigger-110\"");

WriteLiteral("></span>\r\n                    上传\r\n                </button>\r\n            </span>\r" +
"\n        </div>\r\n        <div");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">    <input");

WriteLiteral(" name=\"file\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"file\"");

WriteLiteral(" placeholder=\"上传文件\"");

WriteLiteral("  onchange=\"$(\'#ufile\').val($(\'input[id=file]\').val());\"");

WriteLiteral("/></div>\r\n");

            
            #line 45 "..\..\Areas\Admin\Views\File\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Admin\Views\File\Index.cshtml"
         if (clips.Count > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"glyphicon glyphicon-floppy-disk\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2289), Tuple.Create("\"", 2317)
, Tuple.Create(Tuple.Create("", 2297), Tuple.Create("剪切板共有", 2297), true)
            
            #line 49 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create(" ", 2302), Tuple.Create<System.Object, System.Int32>(clips.Count
            
            #line default
            #line hidden
, 2303), false)
, Tuple.Create(Tuple.Create(" ", 2315), Tuple.Create("项", 2316), true)
);

WriteLiteral(">");

            
            #line 49 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                                                                   Write(clips.Count);

            
            #line default
            #line hidden
WriteLiteral("</i>\r\n            </span>\r\n            <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-pink btn-sm\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2467), Tuple.Create("\"", 2518)
, Tuple.Create(Tuple.Create("", 2477), Tuple.Create("location.href", 2477), true)
, Tuple.Create(Tuple.Create(" ", 2490), Tuple.Create("=", 2491), true)
, Tuple.Create(Tuple.Create(" ", 2492), Tuple.Create("\'/Admin/File/Paste?r=", 2493), true)
            
            #line 52 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                , Tuple.Create(Tuple.Create("", 2514), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 2514), false)
, Tuple.Create(Tuple.Create("", 2516), Tuple.Create("\';", 2516), true)
);

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"glyphicon glyphicon-floppy-save icon-on-right bigger-110\"");

WriteLiteral("></span>\r\n                    粘贴\r\n                </button>\r\n            </span>\r" +
"\n            <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-gray btn-sm\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2803), Tuple.Create("\"", 2853)
, Tuple.Create(Tuple.Create("", 2813), Tuple.Create("location.href", 2813), true)
, Tuple.Create(Tuple.Create(" ", 2826), Tuple.Create("=", 2827), true)
, Tuple.Create(Tuple.Create(" ", 2828), Tuple.Create("\'/Admin/File/Move?r=", 2829), true)
            
            #line 58 "..\..\Areas\Admin\Views\File\Index.cshtml"
                               , Tuple.Create(Tuple.Create("", 2849), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 2849), false)
, Tuple.Create(Tuple.Create("", 2851), Tuple.Create("\';", 2851), true)
);

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"glyphicon glyphicon-floppy-save icon-on-right bigger-110\"");

WriteLiteral("></span>\r\n                    移动\r\n                </button>\r\n            </span>\r" +
"\n            <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-yellow btn-sm\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 3140), Tuple.Create("\"", 3200)
, Tuple.Create(Tuple.Create("", 3150), Tuple.Create("location.href", 3150), true)
, Tuple.Create(Tuple.Create(" ", 3163), Tuple.Create("=", 3164), true)
, Tuple.Create(Tuple.Create(" ", 3165), Tuple.Create("\'/Admin/File/ClearClipboard?r=", 3166), true)
            
            #line 64 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                           , Tuple.Create(Tuple.Create("", 3196), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 3196), false)
, Tuple.Create(Tuple.Create("", 3198), Tuple.Create("\';", 3198), true)
);

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"glyphicon glyphicon-retweet icon-on-right bigger-110\"");

WriteLiteral("></span>\r\n                    清空\r\n                </button>\r\n            </span>\r" +
"\n        </div>\r\n");

            
            #line 70 "..\..\Areas\Admin\Views\File\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    </form>\r\n</div>\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3557), Tuple.Create("\"", 3591)
, Tuple.Create(Tuple.Create("", 3564), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File?r=")
, 3564), false)
            
            #line 76 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3579), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 3579), false)
, Tuple.Create(Tuple.Create("", 3581), Tuple.Create("&sort=name", 3581), true)
);

WriteLiteral(">名称</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3644), Tuple.Create("\"", 3678)
, Tuple.Create(Tuple.Create("", 3651), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File?r=")
, 3651), false)
            
            #line 77 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3666), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 3666), false)
, Tuple.Create(Tuple.Create("", 3668), Tuple.Create("&sort=size", 3668), true)
);

WriteLiteral(">大小</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3731), Tuple.Create("\"", 3770)
, Tuple.Create(Tuple.Create("", 3738), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File?r=")
, 3738), false)
            
            #line 78 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3753), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 3753), false)
, Tuple.Create(Tuple.Create("", 3755), Tuple.Create("&sort=lastwrite", 3755), true)
);

WriteLiteral(">修改时间</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">复制</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">压缩</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">删除</th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 85 "..\..\Areas\Admin\Views\File\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 85 "..\..\Areas\Admin\Views\File\Index.cshtml"
         foreach (var item in fs)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 88 "..\..\Areas\Admin\Views\File\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 88 "..\..\Areas\Admin\Views\File\Index.cshtml"
                 if (item.Directory)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td>&nbsp;&nbsp;<a");

WriteAttribute("href", Tuple.Create(" href=\"", 4123), Tuple.Create("\"", 4159)
, Tuple.Create(Tuple.Create("", 4130), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File?r=")
, 4130), false)
            
            #line 90 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4145), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 4145), false)
);

WriteLiteral(" title=\"进入目录\"");

WriteLiteral(">");

            
            #line 90 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                                                                    Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n");

            
            #line 91 "..\..\Areas\Admin\Views\File\Index.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td>&nbsp;&nbsp;<a");

WriteAttribute("href", Tuple.Create(" href=\"", 4293), Tuple.Create("\"", 4338)
, Tuple.Create(Tuple.Create("", 4300), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File/Download?r=")
, 4300), false)
            
            #line 94 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4324), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 4324), false)
);

WriteLiteral(" title=\"下载文件\"");

WriteLiteral(">");

            
            #line 94 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                                                                             Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n");

            
            #line 95 "..\..\Areas\Admin\Views\File\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 96 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                  Write(item.Size);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 97 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                   Write(item.LastWrite.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

            
            #line 99 "..\..\Areas\Admin\Views\File\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 99 "..\..\Areas\Admin\Views\File\Index.cshtml"
                     if (!clips.Any(e => e.FullName == item.FullName))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4691), Tuple.Create("\"", 4737)
, Tuple.Create(Tuple.Create("", 4698), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File/Copy?r=")
, 4698), false)
            
            #line 101 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4718), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 4718), false)
, Tuple.Create(Tuple.Create("", 4720), Tuple.Create("&f=", 4720), true)
            
            #line 101 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4723), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 4723), false)
);

WriteLiteral(" title=\"复制到剪切板，然后去目标目录粘贴\"");

WriteLiteral(">复制</a>\r\n");

            
            #line 102 "..\..\Areas\Admin\Views\File\Index.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4870), Tuple.Create("\"", 4922)
, Tuple.Create(Tuple.Create("", 4877), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File/CancelCopy?r=")
, 4877), false)
            
            #line 105 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4903), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 4903), false)
, Tuple.Create(Tuple.Create("", 4905), Tuple.Create("&f=", 4905), true)
            
            #line 105 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4908), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 4908), false)
);

WriteLiteral(" title=\"从剪切板移除\"");

WriteLiteral(">取消复制</a>\r\n");

            
            #line 106 "..\..\Areas\Admin\Views\File\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n");

            
            #line 108 "..\..\Areas\Admin\Views\File\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 108 "..\..\Areas\Admin\Views\File\Index.cshtml"
                 if (item.Name.EndsWithIgnoreCase(".zip"))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5120), Tuple.Create("\"", 5167)
, Tuple.Create(Tuple.Create("", 5127), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File/Decompress?r=")
, 5127), false)
            
            #line 110 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5153), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 5153), false)
);

WriteLiteral(" title=\"解压缩到当前目录\"");

WriteLiteral(">解压缩</a></td>\r\n");

            
            #line 111 "..\..\Areas\Admin\Views\File\Index.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5306), Tuple.Create("\"", 5351)
, Tuple.Create(Tuple.Create("", 5313), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File/Compress?r=")
, 5313), false)
            
            #line 114 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5337), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 5337), false)
);

WriteLiteral(" title=\"压缩到当前目录，加上时间后缀\"");

WriteLiteral(">压缩</a></td>\r\n");

            
            #line 115 "..\..\Areas\Admin\Views\File\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5450), Tuple.Create("\"", 5493)
, Tuple.Create(Tuple.Create("", 5457), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File/Delete?r=")
, 5457), false)
            
            #line 116 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5479), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 5479), false)
);

WriteLiteral(" onclick=\"return confirm(\'确认删除？\');\"");

WriteLiteral(">删除</a></td>\r\n            </tr>\r\n");

            
            #line 118 "..\..\Areas\Admin\Views\File\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
